### ISSUE TITLE
Nombre del juego

### ISSUE THREAD

**Issue by MatiasEzr** [MatiasEzr/UNLa#8]
Cual elegimos?
MauroHg commented 4 hours ago
Cuando todavia no sabes como va a ser el juego pero tenes el nombre

**Comment by MauroHg** [comment]
Extra: Nombre a personajes? Mas de un personaje?

**Comment by MatiasEzr** [comment]
Como quedamos? posibilidad de jugar con personaje femenino o masculino?

**Comment by DanyGeier** [comment]
Seria bueno con ambas, un pj masculino y otro femenino
